[package]
name = "FilesharingApp"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.1"
anyhow = "1.0"
tokio-util = { version = "0.7.18", features = ["io"] }
tower-http = { version = "0.6.8", features = ["fs", "normalize-path", "trace"] }
tracing-subscriber = {  version = "0.3.22", features = ["fmt", "env-filter"] }
rand = "0.10.0"
time = { version = "0.3.47", features = ["serde", "parsing", "formatting", "macros", "local-offset"] }
argon2 = "0.5.3"
rand_core = {  version = "0.6.4", features = ["getrandom"] }
clap = { version = "4.5.59", features = ["derive"] }
notify = "8.2.0"
nix = "0.31.1"
rust-embed = "8.11.0"
mime_guess = "2.0.5"