[files."Projektantrag.md"]
hidden = false
password_hash = "$argon2id$v=19$m=19456,t=2,p=1$k6BjhqQSpMCqIE/GwMVE9g$XCPCW5a14oGPfXPUZ9bve4ZV3Zhzgs35hDCcY8SieJg"
tokens = []

[files."Documents.zip"]
hidden = true

[[files."Documents.zip".tokens]]
value = "oNBfbIKCqF37hFZYbq9F5LH9dzaaR4DH"

[[files."Documents.zip".tokens]]
value = "b3cREO8UuxgGoPci8cAZ6DZz38QGhOEi"

[[files."Documents.zip".tokens]]
value = "i6KU0UyMxe8BhzgQtxpeCeKVOuYEKk5H"

[[files."Documents.zip".tokens]]
value = "b9WzSicXnqEyBCj16aBFVMtYTqceIrdB"

[[files."Documents.zip".tokens]]
value = "jsyg2VJ2p2ihpz6H8ngxI4MpcnWlNryT"

[[files."Documents.zip".tokens]]
value = "XUNI7VDA2RtB87k3gcip80VwMmIcqzre"

[[files."Documents.zip".tokens]]
value = "G6fRQLAYMZollCh0gYKEeahJiLyUdVfq"
expires = [
    2026,
    54,
    12,
    5,
    8,
    569567000,
    0,
    0,
    0,
]

[[files."Documents.zip".tokens]]
value = "BwIjDYWXVZk6AE2cRUz0Z6OVgWq8EGNk"
expires = [
    2026,
    61,
    11,
    36,
    57,
    597551700,
    0,
    0,
    0,
]
