[files."Projektantrag.md"]
hidden = false
password_hash = "$argon2id$v=19$m=19456,t=2,p=1$k6BjhqQSpMCqIE/GwMVE9g$XCPCW5a14oGPfXPUZ9bve4ZV3Zhzgs35hDCcY8SieJg"
tokens = []

[files."Documents.zip"]
hidden = true

[[files."Documents.zip".tokens]]
value = "XUNI7VDA2RtB87k3gcip80VwMmIcqzre"

[[files."Documents.zip".tokens]]
value = "BwIjDYWXVZk6AE2cRUz0Z6OVgWq8EGNk"
expires = [
    2026,
    61,
    11,
    36,
    57,
    597551700,
    0,
    0,
    0,
]

[[files."Documents.zip".tokens]]
value = "jSlVeUZXMZp9ZpK5ihbMVQkL7MoMLTAH"

[[files."Documents.zip".tokens]]
value = "XkHrMY4r1ciSTEwwBhyLZLUAKw1Ow9xc"

[files.Empty]
hidden = true
tokens = []
